// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blqbcumymdcexikdmyoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscWJjdW15bWRjZXhpa2RteW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTk3MTgsImV4cCI6MjA3MjIzNTcxOH0.8mEq_Csqeoedjt2300cZPuU6RHpukGf7QS2XZNAzNao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});